export interface MockCourse {
  id: string;
  slug: string;
  title: string;
  summary: string;
  level: 'intro' | 'intermediate' | 'advanced';
  category: string;
  duration: string;
  students: string;
  rating: number;
  thumbnail?: string;
  enrolled?: boolean;
  progress?: number;
  isFavorite?: boolean;
}

export const mockCourses: MockCourse[] = [
  {
    id: '1',
    slug: 'intro-ml',
    title: 'Introduction to Machine Learning',
    summary: 'Build your first ML models and understand core algorithms with hands-on projects',
    level: 'intermediate',
    category: 'AI/ML',
    duration: '8 weeks',
    students: '2.5K',
    rating: 4.8,
    enrolled: true,
    progress: 65,
    isFavorite: true,
  },
  {
    id: '2',
    slug: 'calculus-1',
    title: 'Calculus I',
    summary: 'Master the fundamentals of differential and integral calculus',
    level: 'intro',
    category: 'Mathematics',
    duration: '10 weeks',
    students: '3.2K',
    rating: 4.9,
    enrolled: true,
    progress: 45,
    isFavorite: false,
  },
  {
    id: '3',
    slug: 'linear-algebra',
    title: 'Linear Algebra',
    summary: 'Explore vector spaces, matrices, and linear transformations',
    level: 'intermediate',
    category: 'Mathematics',
    duration: '8 weeks',
    students: '1.8K',
    rating: 4.7,
    enrolled: false,
    isFavorite: true,
  },
  {
    id: '4',
    slug: 'deep-learning',
    title: 'Deep Learning Fundamentals',
    summary: 'Learn neural networks, CNNs, RNNs and modern deep learning architectures',
    level: 'advanced',
    category: 'AI/ML',
    duration: '12 weeks',
    students: '1.5K',
    rating: 4.9,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '5',
    slug: 'data-structures',
    title: 'Data Structures & Algorithms',
    summary: 'Master fundamental data structures and algorithmic problem solving',
    level: 'intermediate',
    category: 'Computer Science',
    duration: '10 weeks',
    students: '4.1K',
    rating: 4.8,
    enrolled: true,
    progress: 30,
    isFavorite: false,
  },
  {
    id: '6',
    slug: 'quantum-mechanics',
    title: 'Introduction to Quantum Mechanics',
    summary: 'Understand the principles of quantum physics and wave-particle duality',
    level: 'advanced',
    category: 'Physics',
    duration: '14 weeks',
    students: '890',
    rating: 4.6,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '7',
    slug: 'web-development',
    title: 'Full Stack Web Development',
    summary: 'Build modern web applications with React, Node.js, and databases',
    level: 'intermediate',
    category: 'Computer Science',
    duration: '12 weeks',
    students: '5.2K',
    rating: 4.9,
    enrolled: false,
    isFavorite: true,
  },
  {
    id: '8',
    slug: 'python-basics',
    title: 'Python Programming Basics',
    summary: 'Learn Python from scratch with practical examples and projects',
    level: 'intro',
    category: 'Computer Science',
    duration: '6 weeks',
    students: '6.8K',
    rating: 4.8,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '9',
    slug: 'statistics',
    title: 'Statistics for Data Science',
    summary: 'Master statistical concepts and their applications in data analysis',
    level: 'intermediate',
    category: 'Mathematics',
    duration: '8 weeks',
    students: '2.9K',
    rating: 4.7,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '10',
    slug: 'nlp',
    title: 'Natural Language Processing',
    summary: 'Build AI systems that understand and generate human language',
    level: 'advanced',
    category: 'AI/ML',
    duration: '10 weeks',
    students: '1.2K',
    rating: 4.8,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '11',
    slug: 'discrete-math',
    title: 'Discrete Mathematics',
    summary: 'Logic, set theory, graph theory, and combinatorics for computer science',
    level: 'intro',
    category: 'Mathematics',
    duration: '10 weeks',
    students: '2.1K',
    rating: 4.6,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '12',
    slug: 'computer-vision',
    title: 'Computer Vision & Image Processing',
    summary: 'Learn how computers see and understand visual information',
    level: 'advanced',
    category: 'AI/ML',
    duration: '12 weeks',
    students: '1.4K',
    rating: 4.7,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '13',
    slug: 'thermodynamics',
    title: 'Classical Thermodynamics',
    summary: 'Study energy, heat, and work in physical systems',
    level: 'intermediate',
    category: 'Physics',
    duration: '8 weeks',
    students: '1.1K',
    rating: 4.5,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '14',
    slug: 'database-systems',
    title: 'Database Systems Design',
    summary: 'Master relational databases, SQL, and database design principles',
    level: 'intermediate',
    category: 'Computer Science',
    duration: '9 weeks',
    students: '3.5K',
    rating: 4.8,
    enrolled: false,
    isFavorite: false,
  },
  {
    id: '15',
    slug: 'differential-equations',
    title: 'Differential Equations',
    summary: 'Solve and apply differential equations in science and engineering',
    level: 'advanced',
    category: 'Mathematics',
    duration: '12 weeks',
    students: '1.6K',
    rating: 4.7,
    enrolled: false,
    isFavorite: false,
  },
];

export const categories = [
  'All Categories',
  'Mathematics',
  'AI/ML',
  'Computer Science',
  'Physics',
];

